services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./metrics-config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - 'localhost:{host_ip_address}'
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    extra_hosts:
      - 'localhost:{host_ip_address}'