services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./metrics-config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - 'localhost:{host_ip_address}'
  grafana:
    image: grafana/grafana
    command:
      '--config /custom/grafana/config.ini'
    volumes:
      - ./metrics-config/grafana/config.yml:/custom/grafana/config.ini
      - ./metrics-config/grafana/dashboards:/etc/dashboards
    ports:
      - "3000:3000"
    extra_hosts:
      - 'localhost:{host_ip_address}'