apiVersion: 1

providers:
  - name: dashboards
    type: file
    updateIntervalSeconds: 30
    options:
      path: /etc/dashboards
      foldersFromFilesStructure: true

datasources:
  - name: Prometheus
    url: http://localhost:9090

auth:
    disable_login_form: true